name: build
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          stable: true
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
          skip-cache: true
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Run Unit tests
        run: go test -race -covermode atomic -coverprofile=profile.cov ./...
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install github.com/mattn/goveralls@latest
          $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
